const Sdata = [
  {
    id: 1,
    title: "Smart whatch",
    price: "1500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-1.png",
  },
  {
    id: 2,
    title: "Tenis nike",
    price: "1000",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-2.png",
  },
  {
    id: 3,
    title: "chamarra café",
    price: "200",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-3.png",
  },
  {
    id: 4,
    title: "bolsas Pandora",
    price: "500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-4.png",
  },
  {
    id: 5,
    title: "Smart whatch",
    price: "1500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-1.png",
  },
  {
    id: 6,
    title: "Tenis nike",
    price: "1000",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-2.png",
  },
  {
    id: 7,
    title: "chamarra café",
    price: "200",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-3.png",
  },
  {
    id: 8,
    title: "bolsas Pandora",
    price: "500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-4.png",
  },
  {
    id: 9,
    title: "bolsas Pandora",
    price: "500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-4.png",
  },
  {
    id: 10,
    title: "Smart whatch",
    price: "1500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-1.png",
  },
  {
    id: 11,
    title: "Tenis nike",
    price: "1000",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-2.png",
  },
  {
    id: 12,
    title: "chamarra café",
    price: "200",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-3.png",
  },
  {
    id: 13,
    title: "bolsas Pandora",
    price: "500",
    starts: "★★★★",
    cover: "../images/SlideCard/slide-4.png",
  },
]
export default Sdata
