const Sdata =[
    {
      id: 7,
      cover: "../images/shops/shops-1.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 8,
      cover: "../images/shops/shops-2.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 9,
      cover: "../images/shops/shops-3.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 10,
      cover: "../images/shops/shops-4.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 11,
      cover: "../images/shops/shops-5.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 12,
      cover: "../images/shops/shops-7.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 13,
      cover: "../images/shops/shops-8.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 14,
      cover: "../images/shops/shops-9.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
    {
      id: 15,
      cover: "../images/shops/shops-10.png",
      title: "Smart whatch",
      price: "1500",
      starts: "★★★★",
    },
  ]
export default Sdata
